name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh admin@92.113.144.178 << 'EOF'
            set -e

            # Переходим в директорию приложения
            cd /home/admin/Telegram_content

            # Подтягиваем все обновления и сбрасываем локальные изменения
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            # Чистая установка зависимостей и сборка
            npm ci
            npm run build

            # Перезапускаем процесс в PM2
            pm2 reload telegram_content
          EOF
